PROGRAM ROTMOL

IMPLICIT NONE
INTEGER NATOMS, NPHI, NTHETA, NGAMA
REAL PHI, THETA, GAMA
REAL, ALLOCATABLE :: XYZ(:,:)
CHARACTER*3, ALLOCATABLE :: ATOM(:)

OPEN(UNIT=1, FILE="input")
OPEN(UNIT=2, FILE="output.xyz")

READ(1,*) NATOMS
ALLOCATE(XYZ(1:NATOMS,1:3),ATOM(1:NATOMS))
READ(1,*) PHI, NPHI, THETA, NTHETA, GAMA, NGAMA

CALL READMOL(NATOMS,ATOM,XYZ)
CALL WRITEMOL(NATOMS,ATOM,XYZ)

CALL ROTX(XYZ,NATOMS,ATOM,PHI,NPHI)


CLOSE(1)
CLOSE(2)

CONTAINS

SUBROUTINE READMOL(NATOMS,ATOM,XYZ)
IMPLICIT NONE
INTEGER i, j, NATOMS
REAL XYZ
CHARACTER*3, ATOM
DIMENSION XYZ(:,:), ATOM(:)

DO 10 i = 1, NATOMS
    READ(1,*) ATOM(i), (XYZ(i,j), j=1,3)
10 CONTINUE

END SUBROUTINE

SUBROUTINE WRITEMOL(NATOMS,ATOM,XYZ)
IMPLICIT NONE
INTEGER i, j, NATOMS
REAL XYZ
CHARACTER*3, ATOM
DIMENSION XYZ(:,:), ATOM(:)

WRITE(2,*) NATOMS
WRITE(2,*) "INPUT"
DO 20 i = 1, NATOMS
    WRITE(2, "(A3, 3F9.4)") ATOM(i), (XYZ(i,j), j=1,3)
20 CONTINUE

END SUBROUTINE

SUBROUTINE ROTX(XYZ,NATOMS,ATOM,PHI,N)
IMPLICIT NONE
CHARACTER*3, ATOM
REAL, PARAMETER :: PIRAD = 3.1415927/180
INTEGER i, j, NATOMS, N, k, l
REAL XYZ, NEWXYZ, XROT, PHI
DIMENSION XYZ(:,:), NEWXYZ(NATOMS,3), XROT(3,3), ATOM(:)
NEWXYZ = XYZ

XROT(1,:) = (/ 0.d0, 0.d0, 0.d0 /)
XROT(2,:) = (/ 0.d0, 0.d0, 0.d0 /)
XROT(3,:) = (/ 0.d0, 0.d0, 0.d0 /)

DO 30 j = 1, N

    XROT(2,2) = COS(PHI*PIRAD*j)
    XROT(3,3) = COS(PHI*PIRAD*j)
    XROT(3,2) = SIN(PHI*PIRAD*j)
    XROT(2,3) = -SIN(PHI*PIRAD*j)

    DO 35 i = 1, NATOMS
        NEWXYZ(i,:) = VECROT(XYZ(i,:),XROT)
    35 CONTINUE

CALL WRITEMOL(NATOMS,ATOM,NEWXYZ)
30 CONTINUE

XYZ = NEWXYZ

END SUBROUTINE

FUNCTION VECROT(VEC, MAT)
IMPLICIT NONE
INTEGER i
REAL VEC, MAT, VECROT
DIMENSION VEC(3), MAT(3,3), VECROT(3)
DO 100 i = 1,3
VECROT(i) = VEC(1)*MAT(i,1) + VEC(2)*MAT(i,2) + VEC(3)*MAT(i,3)
100 CONTINUE

END FUNCTION

END PROGRAM ROTMOL
